### ISSUE TITLE
AtlasI2C is removing the digits to the left of the decimal in readings

### ISSUE THREAD

**Issue by timboring** [AtlasScientific/Raspberry-Pi-sample-code#5]
Instead of return, for example "3.259", the read() method returns ".259". The cause of this is two slice operations which remove the leading digit:

This [line](https://github.com/AtlasScientific/Raspberry-Pi-sample-code/blob/master/AtlasI2C.py#L141) calls the `handle_raspi_glitch()` method with `response[1:]`.

Then this [line](https://github.com/AtlasScientific/Raspberry-Pi-sample-code/blob/master/AtlasI2C.py#L96) inside `handle_raspi_glitch()` is also doing `response[1:]`.

The fix is to only slice the response object once. 

I should also note that this only effects Python 3.

**Comment by Atlas-Scientific** [comment]
Should be fixed now
